version: '3'
services:
  ui:
    build: .
    command: npm start
    volumes:
      - .:/reactiverails-docker-demo
      - /reactiverails-docker-demo/node_modules
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: ui
